name       = "forunittest"
version    = "VERSION"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2023, Seyed Ali Ghasemi"
license    = "LICENSE"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = false

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[dependencies]
kinds   = {git="https://github.com/gha3mi/kinds.git"}
FACE    = {git="https://github.com/szaghi/FACE.git"}

[[test]]
name       = "test"
source-dir = "test"
main       = "test.f90"

[[example]]
name       = "demo"
source-dir = "example"
main       = "demo.f90"