print_msg – ForUnitTest
print_msg Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
14 statements
Source File
private subroutine print_msg(this, condition)
Uses
face
Type Bound
unit_test
Arguments
Type Intent Optional Attributes Name
class(unit_test), intent(inout) :: this
logical, intent(in) :: condition
Calls
Called by
Source Code
   subroutine print_msg(this, condition)
      use face
      class(unit_test), intent(inout) :: this
      logical, intent(in) :: condition
      integer  :: lm
      character(len=20) :: fmt
      lm = 39-len_trim(this%msg)
      write(fmt,'(a,g0,a)') '(a,',lm,'x,a)'
      if (condition) then
         print(fmt), trim(this%msg), colorize('passed.', color_fg='green')
      else
         print(fmt), trim(this%msg), colorize('failed.', color_fg='red')
      end if
   end subroutine print_msg
Call graph
print_msg calls colorize
unit_test_cx0 calls print_msg
unit_test_cx1 calls print_msg
unit_test_cx2 calls print_msg
unit_test_i0 calls print_msg
unit_test_i1 calls print_msg
unit_test_i2 calls print_msg
unit_test_l0 calls print_msg
unit_test_l1 calls print_msg
unit_test_l2 calls print_msg
unit_test_r0 calls print_msg
unit_test_r1 calls print_msg
unit_test_r2 calls print_msg
demo calls check
test calls check