unit_test_l2 – ForUnitTest
unit_test_l2 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
13 statements
Source File
private subroutine unit_test_l2(this, res, expected, msg)
Type Bound
unit_test
Arguments
Type Intent Optional Attributes Name
class(unit_test), intent(inout) :: this
logical, intent(in), dimension(:,:) :: res
logical, intent(in), dimension(:,:) :: expected
character(len=*), intent(in), optional :: msg
Calls
Called by
Source Code
   subroutine unit_test_l2(this, res, expected, msg)
      class(unit_test), intent(inout) :: this
      logical, intent(in), dimension(:,:) :: res, expected
      character(*), intent(in), optional :: msg
      logical :: condition
      if (present(msg)) then
         this%msg = msg
      else
         this%msg = 'forunittest'
      end if
      condition = all(res .eqv. expected)
      call this%print_msg(condition)
   end subroutine unit_test_l2
Call graph
unit_test_l2 calls print_msg
print_msg calls colorize
demo calls check
test calls check