demo – ForUnitTest
demo Program
BSD 3-Clause
7 statements
Source File
Uses
forunittest
Calls
Variables
Type Attributes Name Initial
type(unit_test) :: ut
Source Code
program demo
   ! Use 'forunittest' module to access the unit_test type
   use forunittest, only : unit_test, rk
   implicit none
   ! Declare an object of type 'unit_test'
   type(unit_test) :: ut
   ! call ut%check(res, expected, tol, msg)
   ! Variables 'res' and 'expected' can be of types: real(rk), integer(ik), logical, or complex(rk)
   ! Their ranks can be 0, 1, or 2
   ! 'tol' is an optional real(rk) parameter, default value is 'tiny(0.0_rk)'
   ! 'msg' is an optional character parameter, default value is 'forunittest'
   ! Note: 'res' and 'expected' must have the same type and shape
   call ut%check(res=1.0_rk, expected=1.0_rk, tol=1e-5_rk, msg="demo test 1")
   call ut%check(res=2.0_rk, expected=1.0_rk, tol=1e-5_rk, msg="demo test 2")
end program demo
Call graph
demo calls check
unit_test_cx0 calls print_msg
unit_test_cx1 calls print_msg
unit_test_cx2 calls print_msg
unit_test_i0 calls print_msg
unit_test_i1 calls print_msg
unit_test_i2 calls print_msg
unit_test_l0 calls print_msg
unit_test_l1 calls print_msg
unit_test_l2 calls print_msg
unit_test_r0 calls print_msg
unit_test_r1 calls print_msg
unit_test_r2 calls print_msg
print_msg calls colorize